### ISSUE TITLE
SPI clock frequency changing randomly by 1.6x

### ISSUE THREAD

**Issue by sanktnelson** [msperl/spi-bcm2835#16]
Hi, 
I am trying to read several flir lepton sensors, and while hunting down some transmission problems i found that the SPI clock frequency changes between the set frequency and a ~1.6x slower frequency. When I set 10MHz it sometimes changes to ~6MHz, when I set 18 MHz it changes to 11. This seems likely to be a Hardware or driver issue, since it happens independently ofbthe software I run (tried pylepton and raspberrypi_video). This is on an rpi3 with raspbian. Any clues where this might originate from?

**Comment by msperl** [comment]
I guess you have overclocking  enabled?
SPI clock is directly derived from the core clock, which is changed dynamically with overclocking!
so if you need a fixed speed, then you need to disable overclocking.

**Comment by sanktnelson** [comment]
No, i do not have overclocking enabled. But you were on the right track: It turns out with default settings SPI frequency changes with core clock, as does uart baud rate. Adding "core_freq=250" to the config fixes that.
